### ISSUE TITLE
Wierd sql error when trying to register

### ISSUE THREAD

**Issue by cryptiklemur** [jasongrimes/silex-simpleuser#51]
```
An exception occurred while executing 'SELECT * FROM `users` WHERE `email` = :`email` ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':`email`' at line 1
```

**Comment by cryptiklemur** [comment]
Almost positive that its due to https://github.com/jasongrimes/silex-simpleuser/blob/d73a21f815ee70d2b1f6664370e64055ef2f69f3/src/SimpleUser/UserManager.php#L713

**Comment by ryanhalliday** [comment]
I see you found Pull #41, that will fix this. We just have to wait for that to be accepted. It is critical and hopefully will be merged soon because the current master branch while saying stable, is unusable.
