### ISSUE TITLE
Add ability to change redirect location for post registration

### ISSUE THREAD

**Issue by cryptiklemur** [jasongrimes/silex-simpleuser#54]

**Comment by ryanhalliday** [comment]
This can be changed if we add a configuration option that alters [UserController:119](http://github.com/jasongrimes/silex-simpleuser/blob/adad656f482f781f9d63a099f4db6b9618ddae47/src/SimpleUser/UserController.php#L119).

If this gets done we would likely want to implement something similar for login, which requires defining some Symfony Security options. 

SimpleUser could just provide its own configuration options that then set them within Symfony Security. There is a good guide on the login redirection of Security [here](http://symfony.com/doc/current/cookbook/security/form_login.html).

This has been mentioned before in Issue #20, which was never resolved.

I may do this when I can find some time as its an important feature.
