### ISSUE TITLE
Project Abandoned

### ISSUE THREAD

**Issue by ryanhalliday** [jasongrimes/silex-simpleuser#66]
I don't enjoy writing this message, but I am confident this project has been abandoned. 
The last commit from Jason was Nov 2, 2014. 

Here are three solutions other than this project:
- Use some external OAuth system that is relevant.
- Some other more generic authentication library (Symfony Security, Sentry etc.)
- Roll your own, be sure to use [password_hash](https://secure.php.net/manual/en/function.password-hash.php) and [good security practices](http://www.phptherightway.com/#security).

**Comment by chrootlogin** [comment]
Still the same state? Maybe someone should take over it then.

**Comment by ryanhalliday** [comment]
Exactly the same state sadly. 

To be honest, it could do with a good rewrite so if someone made a similar project that would be just as good as taking over

**Comment by chrootlogin** [comment]
@ry167 I already started doing a rewrite at https://github.com/chrootLogin/silex-userprovider. Feel free to contact me by mail if you want to help coding or create issues and pull requests. 
Would be nice.

**Comment by ryanhalliday** [comment]
Awesome, I have starred it and will look at using that in future projects. I will be sure to send a pull request if I see anything to change.

Once your fork is in a stable state, you could email Jason (jason [at] grimesit [dot] com) and ask him to link to it from this originals Readme.

**Comment by ryanhalliday** [comment]
Closing - repo is dead
